const EnvVariables = {
	RABBITMQ_DEFAULT_USER: "RABBITMQ_DEFAULT_USER",
	RABBITMQ_DEFAULT_PASS: "RABBITMQ_DEFAULT_PASS",
	RABBITMQ_USER: "RABBITMQ_USER",
	RABBITMQ_PASS: "RABBITMQ_PASS",
	RABBITMQ_HOST: "RABBITMQ_HOST",

	RABBITMQ_AUTH_QUEUE: "RABBITMQ_AUTH_QUEUE",
	RABBITMQ_USER_QUEUE: "RABBITMQ_USER_QUEUE",
	RABBITMQ_POST_QUEUE: "RABBITMQ_POST_QUEUE",

	POSTGRES_USER: "POSTGRES_USER",
	POSTGRES_PASSWORD: "POSTGRES_PASSWORD",
	POSTGRES_DB: "POSTGRES_DB",
	POSTGRES_URI: "POSTGRES_URI",
	PGADMIN_DEFAULT_EMAIL: "PGADMIN_DEFAULT_EMAIL",
	PGADMIN_DEFAULT_PASSWORD: "PGADMIN_DEFAULT_PASSWORD",
} as const;

export default EnvVariables;
