const EnvVariables = {
	RABBITMQ_DEFAULT_USER: "RABBITMQ_DEFAULT_USER",
	RABBITMQ_DEFAULT_PASS: "RABBITMQ_DEFAULT_PASS",
	RABBITMQ_USER: "RABBITMQ_USER",
	RABBITMQ_PASS: "RABBITMQ_PASS",
	RABBITMQ_HOST: "RABBITMQ_HOST",

	RABBITMQ_AUTH_QUEUE: "RABBITMQ_AUTH_QUEUE",
	RABBITMQ_USER_QUEUE: "RABBITMQ_USER_QUEUE",
	RABBITMQ_POST_QUEUE: "RABBITMQ_POST_QUEUE",

	POSTGRES_USER: "POSTGRES_USER",
	POSTGRES_PASSWORD: "POSTGRES_PASSWORD",
	POSTGRES_DB: "POSTGRES_DB",
	POSTGRES_PORT: "POSTGRES_PORT",
	POSTGRES_HOST: "POSTGRES_HOST",

	PGADMIN_DEFAULT_EMAIL: "PGADMIN_DEFAULT_EMAIL",
	PGADMIN_DEFAULT_PASSWORD: "PGADMIN_DEFAULT_PASSWORD",

	JWT_SECRET: "JWT_SECRET",
	JWT_EXPIRATION_TIME: "JWT_EXPIRATION_TIME",
	JWT_REFRESH_EXPIRATION_TIME: "JWT_REFRESH_EXPIRATION_TIME",
} as const;

export default EnvVariables;
