version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - .env
